#ifndef CPWINDOW1 
#define CPWINDOW1

#include<lxrad.h>

class CPWindow1:public CWindow
{
  public:
  /*#Controls*/
  CToolButton toolbutton1;
  CToolButton toolbutton2;
  CToolButton toolbutton3;
  CToolButton toolbutton4;
  CToolButton toolbutton5;
  CToolButton toolbutton6;
  CToolButton toolbutton7;
  CToolButton toolbutton8;
  CToolButton toolbutton9;
  CToolButton toolbutton10;
  CToolButton toolbutton11;
  CToolButton toolbutton12;
  CToolButton toolbutton13;
  CToolButton toolbutton14;
  CToolButton toolbutton15;
  CToolButton toolbutton16;
  CToolButton toolbutton17;
  CToolButton toolbutton18;
  CToolButton toolbutton19;
  CToolButton toolbutton20;
  CToolButton toolbutton21;
  CToolButton toolbutton22;
  CToolButton toolbutton23;
  CToolButton toolbutton24;
  CToolButton toolbutton25;
  CToolButton toolbutton26;
  CToolButton toolbutton27;
  CToolButton toolbutton28;
  CToolButton toolbutton29;
  CToolButton toolbutton30;
  CToolButton toolbutton31;
  CToolButton toolbutton32;
  CToolButton toolbutton33;
  CToolButton toolbutton34;
  CToolButton toolbutton35;
  CToolButton toolbutton36;
  CToolButton toolbutton37;
  CToolButton toolbutton38;
  CToolButton toolbutton39;
  CToolButton toolbutton40;
  CToolButton toolbutton41;
  CToolButton toolbutton42;
  CToolButton toolbutton43;
  CToolButton toolbutton44;
  CToolButton toolbutton45;
  CToolButton toolbutton46;
  CToolButton toolbutton47;
  CToolButton toolbutton48;
  CToolButton toolbutton49;
  CToolButton toolbutton50;
  CToolButton toolbutton51;
  CToolButton toolbutton52;
  CToolButton toolbutton53;
  CToolButton toolbutton54;
  CToolButton toolbutton55;
  CToolButton toolbutton56;
  CToolButton toolbutton57;
  CToolButton toolbutton58;
  CToolButton toolbutton59;
  CToolButton toolbutton60;
  CToolButton toolbutton61;
  CToolButton toolbutton62;
  CToolButton toolbutton63;
  CToolButton toolbutton64;
  CToolButton toolbutton65;
  CToolButton toolbutton66;
  CToolButton toolbutton67;
  CToolButton toolbutton68;
  CToolButton toolbutton69;
  CToolButton toolbutton70;
  CToolButton toolbutton71;
  CToolButton toolbutton72;
  CToolButton toolbutton73;
  CToolButton toolbutton74;
  CToolButton toolbutton75;
  CToolButton toolbutton76;
  CToolButton toolbutton77;
  CToolButton toolbutton78;
  CToolButton toolbutton79;
  CToolButton toolbutton80;
  CToolButton toolbutton81;
  CToolButton toolbutton82;
  CToolButton toolbutton83;
  CToolButton toolbutton84;
  CToolButton toolbutton85;
  CToolButton toolbutton86;
  CToolButton toolbutton87;
  CToolButton toolbutton88;
  CToolButton toolbutton89;
  CToolButton toolbutton90;
  CToolButton toolbutton91;
  CToolButton toolbutton92;
  CToolButton toolbutton93;
  CToolButton toolbutton94;
  CToolButton toolbutton95;
  CToolButton toolbutton96;
  CToolButton toolbutton97;
  CToolButton toolbutton98;
  CToolButton toolbutton99;
  CToolButton toolbutton100;
  CMenu menu1;
  CFileDialog filedialog1;
  CFileDialog filedialog2;
  CPMenu menu1_Arquivo;
  CItemMenu menu1_Arquivo_Abrir;
  CItemMenu menu1_Arquivo_Salvar;
  CItemMenu menu1_Arquivo_Sair;
  CPMenu menu1_Editar;
  CPMenu menu1_Ajuda;
  CItemMenu menu1_Editar_Limpar;
  CItemMenu menu1_Ajuda_Sobre;
  /*#Events*/
  void _EvOnCreate(CControl * control);
  void toolbutton1_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton2_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton3_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton4_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton5_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton6_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton7_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton8_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton9_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton10_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton11_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton12_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton13_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton14_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton15_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton16_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton17_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton18_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton19_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton20_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton21_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton22_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton23_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton24_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton25_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton26_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton27_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton28_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton29_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton30_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton31_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton32_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton33_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton34_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton35_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton36_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton37_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton38_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton39_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton40_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton41_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton42_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton43_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton44_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton45_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton46_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton47_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton48_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton49_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton50_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton51_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton52_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton53_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton54_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton55_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton56_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton57_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton58_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton59_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton60_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton61_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton62_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton63_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton64_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton65_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton66_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton67_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton68_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton69_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton70_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton71_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton72_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton73_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton74_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton75_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton76_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton77_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton78_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton79_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton80_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton81_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton82_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton83_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton84_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton85_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton86_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton87_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton88_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton89_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton90_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton91_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton92_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton93_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton94_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton95_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton96_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton97_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton98_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton99_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton100_EvMouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void filedialog1_EvOnClose(int retId);
  void filedialog2_EvOnClose(int retId);
  void menu1_Arquivo_Abrir_EvMenuActive(CControl * control);
  void menu1_Arquivo_Salvar_EvMenuActive(CControl * control);
  void menu1_Arquivo_Sair_EvMenuActive(CControl * control);
  void menu1_Editar_Limpar_EvMenuActive(CControl * control);
  void menu1_Ajuda_Sobre_EvMenuActive(CControl * control);

  /*#Others*/
  CPWindow1(void);
  void toolbuttonMouseButtonPress(CControl* control,uint button,uint x,uint y,uint mask);
};
 extern CPWindow1 Window1 ;

#endif /*#CPWINDOW1*/

