.TH PICSIMLAB "1" "March 2020" "PICSimLab" "User Commands"
.SH NAME
PICSimLab \- PIC Simulator Laboratory
.SH SYNOPSIS
.B picsimlab 
.I <pwz_file>

.SH DESCRIPTION
This command loads picsimlab simulator and can takes one argument (picsimlab workspace pzw file).
The PICSimLab is a realtime emulator of development boards with integrated MPLABX/avr-gdb debugger.
PICSimLab supports picsim microcontrollers (PIC16F84, PIC16F628, PIC16F648, PIC16F777, PIC16F877A, 
PIC18F452, PIC18F4520, PIC18F4550 and PIC18F4620) and simavr microcontrollers (ATMEGA328). PICSimLab 
have integration with MPLABX/Arduino IDE for programming the boards microcontrollers.
.SH AUTHOR
This manual page was written by LcGamboa <lcgamboa@yahoo.com> for the
Debian system. Permission is granted to copy, redistribute and/or modify this
document under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or (at your
option) any later version.
.SH "SEE ALSO"
.PP
.BR arduino (1),
.BR simavr (1),


