CC =  x86_64-w64-mingw32-g++

FLAGS = -Wall -ggdb -D_WIN_ `x86_64-w64-mingw32-msw-unicode-3.1  --cxxflags ` 

LIBS = -llxrad `x86_64-w64-mingw32-msw-unicode-3.1  --libs` 

OBJS = premota.o remota1.o serial.o 

all: $(OBJS)
	$(CC) $(FLAGS) $(OBJS)  -oremota.exe $(LIBS)
	mv *.exe ../../picsimlab_0.7.0_win64/

%.o: %.cc
	$(CC) -c $(FLAGS) $< 

run: all
	wine2 remota.exe

install:

clean:
	rm -f remota.exe *.o core 
