name: macOS release

on:
  workflow_run:
    workflows:
      - macOS build
    types: [completed]

jobs:
  releaseMacOS:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Download dmg images
        uses: actions/download-artifact@v8
        with:
          run-id: ${{ github.event.workflow_run.id }}
          path: release_assets
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Rename dmg images
        run: |
          mkdir release_assets_ready
          mv release_assets/macos-26/PICSimLab.dmg release_assets_ready/PICSimLab-nightly-arm64.dmg
          mv release_assets/macos-26-intel/PICSimLab.dmg release_assets_ready/PICSimLab-nightly-x86_64.dmg

      - name: Remove the old nightly release
        uses: ClementTsang/delete-tag-and-release@v0.3.1
        with:
          delete_release: true
          tag_name: latestbuild_macos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Latest code build release
        uses: softprops/action-gh-release@v3
        with:
          prerelease: true
          files: release_assets_ready/*
          tag_name: latestbuild_macos
          target_commitish: ${{ github.event.workflow_run.head_sha }}
